---
- name: install dependencies from apt
  apt: pkg={{item}} state=present
  with_items:
    - python-apt
    - python-pycurl

- include: freight.yml
- include: gpg.yml

- name: create freight.conf
  template: src=freight.conf.j2 dest=/etc/freight.conf owner=root
